### ISSUE TITLE
Doesn't build with GHC-8.6.1

### ISSUE THREAD

**Issue by hasufell** [vincenthz/hs-memory#69]
```
[20 of 29] Compiling Data.ByteArray.Sized ( Data/ByteArray/Sized.hs, /home/hasufell/git/hs-memory/dist-newstyle/build/x86_64-linux/ghc-8.6.1/memory-0.14.16/build/Data/ByteArray/Sized.o )

Data/ByteArray/Sized.hs:135:22: error:
    • Expected kind ‘* -> Nat -> Nat’,
        but ‘Base.PrimSize ty’ has kind ‘Nat’
    • In the second argument of ‘(~)’, namely ‘(Base.PrimSize ty * n)’
      In the instance declaration for ‘ByteArrayN nbytes (BlockN n ty)’
    |
135 |          , nbytes ~ (Base.PrimSize ty * n)
    |                      ^^^^^^^^^^^^^^^^^^^^
```

**Comment by NicolasDP** [comment]
fixed in #68

**Comment by athas** [comment]
Could you also upload a new release on Hackage?  I still see only the incompatible 0.14.16.
