### ISSUE TITLE
Doesn't compile on GHC 9.0.1 due to unsafeCoerce#

### ISSUE THREAD

**Issue by emberdart** [vincenthz/hs-memory#84]
```
Data/ByteArray/ScrubbedBytes.hs:93:71: error:
    Variable not in scope:
      unsafeCoerce# :: MutableByteArray# RealWorld -> ByteArray#
   |
93 |                 let !scrubber = (getScrubber sz) (byteArrayContents# (unsafeCoerce# mbarr))
   |                                                                       ^^^^^^^^^^^^^

Data/ByteArray/ScrubbedBytes.hs:151:38: error:
    Variable not in scope:
      unsafeCoerce# :: MutableByteArray# RealWorld -> ByteArray#
    |
151 |     a <- f (Ptr (byteArrayContents# (unsafeCoerce# mba)))

Data/ByteArray/Bytes.hs:90:38: error:
    Variable not in scope:
      unsafeCoerce# :: MutableByteArray# RealWorld -> ByteArray#
   |
90 |     a <- f (Ptr (byteArrayContents# (unsafeCoerce# mba)))
```

**Comment by emberdart** [comment]
This workaround Nix derivation override helps:

```nix
{
  memory = (self.callHackage "memory" "0.15.0" {}).overrideDerivation(self: {
    prePatch = ''
      sed -zi 's/import\(\s\+\)GHC.Prim/import\1GHC.Prim hiding (unsafeCoerce#)\nimport\1GHC.Exts (unsafeCoerce#)/' Data/ByteArray/Bytes.hs
      sed -zi 's/import\(\s\+\)GHC.Prim/import\1GHC.Prim hiding (unsafeCoerce#)\nimport\1GHC.Exts (unsafeCoerce#)/' Data/ByteArray/ScrubbedBytes.hs
    '';
  });
}
```

**Comment by sjakobi** [comment]
As a Hackage trustee I have made a revision to v0.15.0 to prevent it from building with GHC 9.0: http://hackage.haskell.org/package/memory-0.15.0/revisions/

Also note that this PR is intended to fix the issue: https://github.com/vincenthz/hs-memory/pull/81

**Comment by sjakobi** [comment]
The v0.16.0 release builds with GHC 9.0.1: http://hackage.haskell.org/package/memory-0.16.0

Thanks @vincenthz! :)

**Comment by ysangkok** [comment]
@danwdart This can be closed.
